### ISSUE TITLE
Cleanup job timeouts, while cleaning up huge amount of cache.

### ISSUE THREAD

**Issue by skatkov** [bsm/activesupport-cache-database#27]
We have 34 GB of cache that we tried to clean-up with latest modification to cleanup method -- and our job constantly timeout doing first run of cleanup.

https://github.com/bsm/activesupport-cache-database/pull/24

Should we introduce a more gradual cleanup? batch cleanup?

**Comment by dim** [comment]
I assume you could add a limit to your cleanup, but I assume this will not happen as much again in the future, once you are cleaning up more regularly. I suggest that you run `while Model.created_before.exist?; Model.created_before.limit(1000).delete_all; end` in the console once :)

**Comment by skatkov** [comment]
Yeah, we did just that. On our application we managed to batch delete it with 10000 limit.

I'm wondering, if cache will be written at a rate that exceeds that. We might want to have this limit parameter for a cleanup method too?

**Comment by skatkov** [comment]
This was resolved. Closing.

https://github.com/bsm/activesupport-cache-database/pull/24
