### ISSUE TITLE
Why don't you recommend to use this as a Rails cache store?

### ISSUE THREAD

**Issue by thawatchai** [bsm/activesupport-cache-database#8]
> To use as a Rails cache store (not recommended!)

This gem is a great idea. I'm wondering why don't you recommend to use this as a Rails cache store?

**Comment by dim** [comment]
I think this is a comment from a distant past, I don't see a reason why you couldn't use it as a Rails cache store these days. I assume the original idea behind `Rails.cache` (i.e. memcache, redis, etc) is to allow users to bypass the RDBMS with something "faster", but that's relative term.

**Comment by thawatchai** [comment]
Wonderful!! I think speed of cache is one thing, but caching is a matter of design. Even this cache uses RDBMS, retrieving a single record is much faster than a complex query. So, this gem will help if we design the caching to benefit from it.

BTW, could you remove the comment in README? I think it would attract more people to use this gem if they can use it as a Rails cache store.

**Comment by dim** [comment]
Already: https://github.com/bsm/activesupport-cache-database#usage ;)
